### ISSUE TITLE
Baseline ordering in calc_blpair_reds

### ISSUE THREAD

**Issue by mkolopanis** [HERA-Team/hera_pspec#188]
I'm not sure if this is due to and upstream update or not, but there seems to be a bug in the ordering of the baselines in calc_blpair_reds on a fresh conda environment (see test output below). Could probably be verified or not by restarting travis build for master.

```
(py2) matthew@cosmos:~/src/hera_pspec (master)$ nosetests hera_pspec --with-coverage --cover-package=hera_pspec 
/home/matthew/anaconda/envs/py2/lib/python2.7/site-packages/astropy/time/core.py:750: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif longitude == 'greenwich':
.................................divide by zero encountered in divide
........invalid value encountered in sqrt
..........................F.F.........................................
======================================================================
FAIL: test_testing.test_uvpspec_from_data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matthew/anaconda/envs/py2/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/matthew/work/src/hera_pspec/hera_pspec/tests/test_testing.py", line 46, in test_uvpspec_from_data
    154169, 167168, 168169])), 0)
AssertionError: 6 != 0

======================================================================
FAIL: test_calc_blpair_reds (test_utils.Test_Utils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matthew/work/src/hera_pspec/hera_pspec/tests/test_utils.py", line 187, in test_calc_blpair_reds
    nt.assert_equal(blps[0], [((24, 37), (25, 38)), ((24, 37), (24, 37))])
AssertionError: Lists differ: [((37, 24), (38, 25)), ((37, 2... != [((24, 37), (25, 38)), ((24, 3...

First differing element 0:
((37, 24), (38, 25))
((24, 37), (25, 38))

- [((37, 24), (38, 25)), ((37, 24), (37, 24))]
+ [((24, 37), (25, 38)), ((24, 37), (24, 37))]

Name                          Stmts   Miss  Cover
-------------------------------------------------
hera_pspec/__init__.py            8      0   100%
hera_pspec/container.py         157      8    95%
hera_pspec/conversions.py        94     11    88%
hera_pspec/data/__init__.py       1      0   100%
hera_pspec/grouping.py          377     11    97%
hera_pspec/noise.py              48      4    92%
hera_pspec/parameter.py           8      0   100%
hera_pspec/plot.py              420     20    95%
hera_pspec/pspecbeam.py         164      9    95%
hera_pspec/pspecdata.py        1041     38    96%
hera_pspec/pstokes.py            89      7    92%
hera_pspec/utils.py             355      5    99%
hera_pspec/uvpspec.py           742     19    97%
hera_pspec/uvpspec_utils.py     324      5    98%
hera_pspec/version.py            34      1    97%
-------------------------------------------------
TOTAL                          3862    138    96%
----------------------------------------------------------------------
Ran 111 tests in 350.832s

FAILED (failures=2)
```

**Comment by philbull** [comment]
This seems to work OK on a fresh (uncached) build of `hera_pspec` in Travis. Closing for now, but please re-open if you see the problem again...
